# Generated by Django 4.1 on 2023-02-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('name', models.CharField(default='Angebotname', max_length=100, verbose_name='Angebot Name')),
                ('subtitel', models.CharField(default='Subtitel', max_length=100, verbose_name='Subtitel')),
                ('kurzbeschrieb', models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb')),
                ('bild', models.CharField(default='gis.webp', max_length=100, verbose_name='Bild')),
                ('video', models.CharField(blank=True, max_length=50, verbose_name='Video Name (aus static Ordner)')),
                ('cards_titel', models.CharField(default='Angebot Cards Titel', max_length=100, verbose_name='Angebot Cards Titel')),
                ('cards_beschrieb', models.TextField(default='Angebot Cards Beschrieb', verbose_name='Angebot Cards Beschrieb')),
            ],
            options={
                'verbose_name_plural': 'Angebote',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Titel', max_length=100, verbose_name='Titel')),
                ('subtitel', models.TextField(default='Subtitel', verbose_name='Subtitel')),
                ('metadaten', models.TextField(blank=True, verbose_name='Metadaten')),
                ('kurzbeschrieb', models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb')),
                ('video', models.CharField(blank=True, max_length=50, verbose_name='Video ID')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht')),
                ('datum', models.DateField(verbose_name='Publizierungsdatum')),
            ],
            options={
                'verbose_name_plural': 'Kontakt Nachrichten',
            },
        ),
        migrations.CreateModel(
            name='Preisplanfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titel')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name_plural': 'Preisplan Features',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=100, verbose_name='Logo')),
                ('firma', models.CharField(max_length=100, verbose_name='Firma')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'Stakeholders',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Testimonial Text')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.angebot')),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Referenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Title', max_length=100, verbose_name='Titel')),
                ('kurzbeschrieb', models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb')),
                ('bild', models.CharField(blank=True, max_length=50, verbose_name='Bild')),
                ('video', models.CharField(blank=True, max_length=50, verbose_name='Video ID')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.angebot')),
                ('stakeholder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Referenzen',
            },
        ),
        migrations.CreateModel(
            name='Preisplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('name', models.CharField(default='Preisplan Name', max_length=50, verbose_name='Name')),
                ('preis', models.CharField(max_length=50, verbose_name='Preis')),
                ('einheit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('popular', models.BooleanField(default=False, verbose_name='Populär')),
                ('features', models.ManyToManyField(blank=True, to='multimediawerk.preisplanfeature')),
            ],
            options={
                'verbose_name_plural': 'Preispläne',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100, verbose_name='Title')),
                ('kurzbeschrieb', models.TextField(verbose_name='Kurzbeschrieb')),
                ('datum', models.DateField(verbose_name='Publizierungsdatum')),
                ('teaser_img', models.CharField(max_length=100, verbose_name='Vorschaubild')),
                ('url', models.URLField(verbose_name='URL zum Post')),
                ('verfasser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Blogposts',
            },
        ),
        migrations.CreateModel(
            name='AngebotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht')),
                ('datum', models.DateField(verbose_name='Publizierungsdatum')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.angebot')),
                ('preisplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multimediawerk.preisplan')),
            ],
            options={
                'verbose_name_plural': 'Angebot Nachrichten',
            },
        ),
        migrations.AddField(
            model_name='angebot',
            name='cards',
            field=models.ManyToManyField(blank=True, to='multimediawerk.card'),
        ),
        migrations.AddField(
            model_name='angebot',
            name='preise',
            field=models.ManyToManyField(blank=True, to='multimediawerk.preisplan'),
        ),
    ]
