# Generated by Django 4.1 on 2023-03-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimediawerk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bild',
            field=models.CharField(default='gis.webp', max_length=50, verbose_name='Bild ID'),
        ),
    ]
