# Generated by Django 4.1 on 2022-08-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angebot',
            options={'verbose_name_plural': 'Angebote'},
        ),
    ]
