# Generated by Django 4.1 on 2022-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0002_alter_angebot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='angebot',
            name='bild',
            field=models.CharField(default='bild.jpeg', max_length=50, verbose_name='Bildname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='angebot',
            name='kurzbeschrieb',
            field=models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='angebot',
            name='name',
            field=models.CharField(default='Angebot', max_length=100, verbose_name='Angebot Name'),
            preserve_default=False,
        ),
    ]
