# Generated by Django 4.1 on 2022-09-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0003_angebot_bild_angebot_kurzbeschrieb_angebot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angebot',
            name='bild',
        ),
        migrations.AddField(
            model_name='angebot',
            name='subtitel',
            field=models.TextField(default='Subtitle', verbose_name='Subtitel'),
        ),
        migrations.AddField(
            model_name='angebot',
            name='video',
            field=models.CharField(blank=True, max_length=50, verbose_name='Video ID'),
        ),
    ]
