# Generated by Django 4.1 on 2022-09-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0004_remove_angebot_bild_angebot_subtitel_angebot_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Titel', max_length=100, verbose_name='Angebot Name')),
                ('kurzbeschrieb', models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb')),
                ('subtitel', models.TextField(default='Subtitel', verbose_name='Subtitel')),
                ('metadaten', models.CharField(blank=True, max_length=200, verbose_name='Metadaten')),
                ('video', models.CharField(blank=True, max_length=50, verbose_name='Video ID')),
                ('link', models.TextField(blank=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AlterField(
            model_name='angebot',
            name='kurzbeschrieb',
            field=models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='name',
            field=models.CharField(default='Angebotname', max_length=100, verbose_name='Angebot Name'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='subtitel',
            field=models.TextField(default='Subtitel', verbose_name='Subtitel'),
        ),
        migrations.AlterField(
            model_name='angebot',
            name='video',
            field=models.CharField(blank=True, max_length=50, verbose_name='Video Name (aus static Ordner)'),
        ),
        migrations.CreateModel(
            name='Angebotbeispiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bildname', models.CharField(max_length=50, verbose_name='Bildname')),
                ('titel', models.CharField(default='Title', max_length=100, verbose_name='Title')),
                ('kurzbeschrieb', models.TextField(default='Kurzbeschrieb', verbose_name='Kurzbeschrieb')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kartenwerk.angebot')),
            ],
            options={
                'verbose_name_plural': 'Angebotsbeispiele',
            },
        ),
        migrations.AddField(
            model_name='angebot',
            name='cards',
            field=models.ManyToManyField(blank=True, to='kartenwerk.card'),
        ),
    ]
