# Generated by Django 4.1 on 2022-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0005_card_alter_angebot_kurzbeschrieb_alter_angebot_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
        migrations.AlterField(
            model_name='card',
            name='metadaten',
            field=models.TextField(blank=True, verbose_name='Metadaten'),
        ),
        migrations.AlterField(
            model_name='card',
            name='titel',
            field=models.CharField(default='Titel', max_length=100, verbose_name='Titel'),
        ),
    ]
