# Generated by Django 4.1 on 2022-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0006_remove_card_link_alter_card_metadaten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angebot',
            name='bild',
            field=models.CharField(default='gis.webp', max_length=100, verbose_name='Bild'),
        ),
    ]
