# Generated by Django 4.1 on 2022-09-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0007_angebot_bild'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angebotbeispiel',
            old_name='bildname',
            new_name='bild',
        ),
    ]
