# Generated by Django 4.1 on 2022-09-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0010_alter_angebot_subtitel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angebot',
            old_name='angebot_cards_beschrieb',
            new_name='cards_beschrieb',
        ),
        migrations.RenameField(
            model_name='angebot',
            old_name='angebot_cards_titel',
            new_name='cards_titel',
        ),
    ]
