# Generated by Django 4.1 on 2022-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0011_rename_angebot_cards_beschrieb_angebot_cards_beschrieb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preisplanfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titel')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name_plural': 'Preisplan Features',
            },
        ),
        migrations.CreateModel(
            name='Preisplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('preis', models.CharField(max_length=50, verbose_name='Preis')),
                ('einheit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('features', models.ManyToManyField(blank=True, to='kartenwerk.preisplanfeature')),
            ],
            options={
                'verbose_name_plural': 'Preispläne',
            },
        ),
        migrations.AddField(
            model_name='angebot',
            name='preise',
            field=models.ManyToManyField(blank=True, to='kartenwerk.preisplan'),
        ),
    ]
