# Generated by Django 4.1 on 2022-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0012_preisplanfeature_preisplan_angebot_preise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preisplan',
            name='titel',
        ),
        migrations.AddField(
            model_name='preisplan',
            name='name',
            field=models.CharField(default='Preisplan Name', max_length=50, verbose_name='Name'),
        ),
    ]
