# Generated by Django 4.1 on 2022-09-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0014_preisplan_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preisplan',
            options={'ordering': ['order'], 'verbose_name_plural': 'Preispläne'},
        ),
    ]
