# Generated by Django 4.1 on 2022-09-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0015_alter_preisplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preisplan',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Populär'),
        ),
    ]
