# Generated by Django 4.1 on 2022-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0016_preisplan_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='angebot',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
