# Generated by Django 4.1 on 2022-09-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0017_angebot_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='angebot',
            options={'ordering': ['order'], 'verbose_name_plural': 'Angebote'},
        ),
    ]
