# Generated by Django 4.1 on 2022-09-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0020_referenz_stakeholder_remove_testimonial_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenz',
            name='stakeholder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kartenwerk.stakeholder'),
        ),
    ]
