# Generated by Django 4.1 on 2022-09-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0021_alter_referenz_stakeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='firma',
            field=models.CharField(max_length=100, verbose_name='Firma'),
        ),
    ]
