# Generated by Django 4.1 on 2022-09-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0023_alter_referenz_bild_alter_referenz_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenz',
            name='titel',
            field=models.CharField(default='Title', max_length=100, verbose_name='Titel'),
        ),
    ]
