# Generated by Django 4.1 on 2022-11-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0025_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenz',
            name='video',
            field=models.CharField(blank=True, max_length=50, verbose_name='Video ID'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('datum', models.DateField(verbose_name='Publizierungsdatum')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kartenwerk.angebot')),
            ],
            options={
                'verbose_name_plural': 'Nachrichten',
            },
        ),
    ]
