# Generated by Django 4.1 on 2022-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0026_alter_referenz_video_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='bemerkung',
        ),
        migrations.AddField(
            model_name='message',
            name='nachricht',
            field=models.TextField(blank=True, verbose_name='Nachricht'),
        ),
    ]
