# Generated by Django 4.1 on 2022-11-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0027_remove_message_bemerkung_message_nachricht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='product',
            new_name='angebot',
        ),
    ]
