# Generated by Django 4.1 on 2022-11-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0028_rename_product_message_angebot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='preisplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kartenwerk.preisplan'),
            preserve_default=False,
        ),
    ]
