# Generated by Django 4.1 on 2023-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0029_message_preisplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='AngebotMessage',
        ),
    ]
