# Generated by Django 4.1 on 2023-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartenwerk', '0030_rename_message_angebotmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht')),
                ('datum', models.DateField(verbose_name='Publizierungsdatum')),
            ],
            options={
                'verbose_name_plural': 'Kontakt Nachrichten',
            },
        ),
        migrations.AlterModelOptions(
            name='angebotmessage',
            options={'verbose_name_plural': 'Angebot Nachrichten'},
        ),
    ]
